.github/workflows/integration_test.yaml
metadata.yaml
src/agent.py
src/jenkins.py
tests/integration/conftest.py
tests/integration/pre-run-script.sh
tests/integration/pre_run_script.sh
tests/integration/test_agent.py

This PR adds a Cross-Model Cross Controller integration test with the Jenkins agent machine charm.
Other changes:
- remove duplicate str conversion
- increase plugins install timeout
- rename to jenkins-k8s from jenkins-k8s-operator

test: machine charm integration

---

metadata.yaml
src-docs/agent.py.md
src-docs/charm.py.md
src-docs/jenkins.py.md
src-docs/state.py.md
src/agent.py
src/charm.py
src/jenkins.py
src/state.py
tests/conftest.py
tests/integration/conftest.py
tests/integration/test_agent.py
tests/unit/conftest.py
tests/unit/test_agent.py
tests/unit/test_jenkins.py
tests/unit/test_state.py

This PR introduces the new agent_v0_interface under the `agent` relation.
It further addresses:
- code styling changes to import directly from the `ops` pacakge.
- removing `self._jenkins_container` replacing it as single use container get
- 1:1 callback methods for each event handler
- remove registered agent on relation broken.

feat: new agent_v0_interface support

---

.gitignore
docs/explanation/agent-deprecated-relation.md
docs/how-to/configure-update-time-range.md
docs/how-to/get-admin-password.md
docs/how-to/integrate-with-machine-agents.md
docs/index.md
docs/reference/actions.md
docs/reference/configurations.md
docs/reference/integrations.md
docs/tutorial/getting-started.md
metadata.yaml

The docs are based on the [diataxis framework](https://diataxis.fr/) and covers the following:
- Introduction
- Tutorial
- Deploying jenkins-k8s
- Relating jenkins-k8s with jenkins-agent-k8s
- Getting admin password
- Reference
- agent relation to jenkins-agent-k8s and jenkins-agent through CMR
- How-to
- configure upate-time-range
- get-admin-password
- Explanation
- agent-deprecated relation
Additonally, charm artifact has been added to the .gitignore.

docs: basic charm docs

---

metadata.yaml
src-docs/jenkins.py.md
src-docs/state.py.md
src/state.py
tests/integration/conftest.py
tests/integration/test_k8s_agent.py

Allow more than one agent application to connect to the `agent` relation endpoint.
This would allow k8s and machine agents to share a same Jenkins server.
None.
`state.py`'s method of getting relation are changed from a singular relation fetching method `relations.get(RELATION_NAME)` to `relations[RELATION_NAME]`.
None.

fix: >1 app per relation

---

tests/integration/conftest.py

Applicable spec: NA
Use function level client fixtures to avoid Unauthorized 401 error in integration tests.
To reduce flakiness of the integration tests.
N/A
N/A
None.

fix: use function level client fixture

---

.github/workflows/integration_test.yaml
tests/integration/conftest.py
tests/integration/helpers.py
tests/integration/test_plugins.py

Filter the unit that has run the postbuildscript job so that the tests are less flaky.
To make the tests less flaky.
None.
None.
None.

fix: filter unit running job

---

jenkins_rock/rockcraft.yaml
src/jenkins.py
tests/integration/helpers.py
tests/integration/test_k8s_agent.py
tests/unit/conftest.py

Bump Jenkins LTS version to latest release & Jenkins plugin manager to latest patch.
To support latest version of Jenkins.
None.
None.
None.

chore: update jenkins lts version

---

tests/integration/test_plugins.py

Adds a test for blueocean plugin frontend load.
To add support for blueocean plugin.
None.
None.
None.

test: blueocean plugin

---

tests/integration/helpers.py
tests/integration/test_plugins.py

Adds integration test to ssh_agent plugin. Only a UI test is done rather than a functional test since installation of ssh-agent on the jenkins agent and testing for it is out of the scope of this repository.
To test for the commonly used plugin: ssh_agent.
None.
None.
None.

test: ssh_agent plugin

---

src-docs/jenkins.py.md
src/charm.py
src/jenkins.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_jenkins.py

To use API token instead of insecure password. This is also useful when changing the security realm for Jenkins to non-Jenkins database user authorization, where the password will no longer work while api tokens continue to work.
To keep control of Jenkins even when security realm changes.
None.
Added a `_get_api_credentials` in `jenkins.py` alongside `get_admin_credentials` and internal client creator methods now call `_get_api_credentials` instead of `get_admin_credentials`.
None.

fix: use api token instaed of password

---

lib/charms/traefik_k8s/v1/ingress.py
metadata.yaml
src-docs/charm.py.md
src-docs/ingress.py.md
src/charm.py
src/ingress.py
tests/integration/conftest.py
tests/integration/test_ingress.py

Add [ingress v2 support](https://github.com/canonical/charm-relation-interfaces/tree/main/interfaces/ingress/v2)
Support for ingress v2 will be needed for integration with the oauthkeeper charm
N/A
New ingress module
Added ingress v2 lib

Ingress v2 support

---

tests/integration/test_jenkins.py
tests/integration/test_plugins.py
tests/unit/conftest.py
tests/unit/test_actions.py
tests/unit/test_agent.py
tests/unit/test_charm.py
tests/unit/test_jenkins.py

Refactor raising exceptions via lambda to `unittest.mock`'s `side_effect` function.
Use Pythonic testing syntax.
None.
None.
None.

test: refactor raise exceptions lambda

---

.github/workflows/integration_test.yaml
requirements.txt
tests/integration/conftest.py
tests/integration/pre_run_script.sh
tests/integration/test_jenkins.py
tox.ini

To fix integration tests that rely on juju 2.9, the latest COS is not backwards compatible with juju 2.9.
Our operator workflows use juju 2.9 and many of the prod environments are in 2.9.
None.
None.
None.

fix: juju 3.1 compatible cos stack

---

src-docs/actions.py.md
src-docs/agent.py.md
src-docs/charm.py.md
src-docs/state.py.md
src/actions.py
src/agent.py
src/charm.py
src/jenkins.py
src/state.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_actions.py
tests/unit/test_charm.py
tests/unit/test_jenkins.py
tests/unit/test_state.py

Prevent any service events (pebble_ready, storage_ready, update_status, actions) from continuing before all preconditions (container ready & storage mounted) are ready.
Prevent unstable behavior of Jenkins when the service starts before the storage has been properly mounted.
N/A
`charm.py` - event handlers have storage attached check.
`actions.py` - action event handlers have storage attached check.
`agent.py` - agent relation handlers have storage attached check.
None.

fix: prevent hooks before preconditions ready

---

src/agent.py
src/charm.py

Applicable spec: N/A.
Adds comments justifying the deferred events.
Defer is usually not recommended to use. However, since every handler surgically does an operation that doesn't globally handle the service restarts/logic, defer must be used in many cases. The comments help reason about the use of defers.
None.
None(comments added).
None.

chore: comment on deferred events.

---

jenkins_rock/rockcraft.yaml

Bump to the latest Jenkins LTS version to mitigate CVEs.
To mitigate CVEs.
None.
None.

chore: bump jenkins-k8s LTS version

---

src/charm.py
tests/unit/conftest.py
tests/unit/test_charm.py
tox.ini

Add an [open port to k8s service](https://juju.is/docs/sdk/open-a-kubernetes-port-in-your-charm#heading--add-a-kubernetes-service-port-to-your-charm) which is a good information for SREs when deploying the charm.
Helps annotate the k8s service with port definitions.
The pebble ready event sets open port when charm is successfully initialized.
`charm.py`
None.

feat: open port

---

.github/workflows/integration_test.yaml
tox.ini

Use `edge` self-hosted runner for integration test
- Reduce load on GitHub-provided runner on the organisation.
- Test out the edge revision of github-runner charm on this repo.

Use self-hosted runner for integration test

---

.github/workflows/comment.yaml
.github/workflows/integration_test.yaml
tests/integration/helpers.py
tests/integration/test_jenkins.py
tests/integration/test_plugins.py

!This is a draft PR!
1. The workflow fails due to insufficient permissions.
2. The integration tests fails due to an update with blueocean plugin and a bug in jenkins-plugins-manager which doesn't resolve the dependency correctly and one of the dependent plugin downstream is not downloaded which causes the blueocean plugin to break.
To make the integration tests pass.
none.
none.
none.
- [ x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied

fix: integration test & workflow

---

src/charm.py
tests/unit/test_charm.py

Storage mount event should be handled if the container was not yet ready.
Juju `set_port` on kubernetes errors, contrary to what the documentation suggests. [link to documentation](https://juju.is/docs/sdk/hook-tool#heading--networking).
```
2024-01-02 00:15:54 ERROR juju.worker.uniter.context context.go:1199 cannot apply changes: cannot retrieve ports for unit "jenkins-k8s/0": unit "jenkins-k8s/0" is not assigned to a machine
2024-01-02T00:15:54.898Z [container-agent] 2024-01-02 00:15:54 ERROR juju.worker.uniter.operation runhook.go:153 hook "jenkins-pebble-ready" (via hook dispatching script: dispatch) failed: cannot apply changes: cannot retrieve ports for unit "jenkins-k8s/0": unit "jenkins-k8s/0" is not assigned to a machine
```
The storage mount event does not …

fix: storage mount defer event & set port

---

jenkins_rock/rockcraft.yaml
src-docs/jenkins.py.md
src-docs/state.py.md
src/actions.py
src/agent.py
src/charm.py
src/jenkins.py
src/state.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_jenkins.py
tests/unit/test_state.py

The storage mount, even if `/proc/mount` returns the valid path, isn't quite mounted with proper permissions and the path is wiped out on mount. This change waits for the storage-ready hook to fire first, changing the permissions for the Jenkins home directory, making sure that Jenkins installation happens *after* the storage has been properly mounted.
When storage gets attached during jenkins installation (the /proc/mount will have /var/lib/jenkins) directory - Jenkins errors with file permissions error. This change will make sure that the `storage-mounted` hook will be handled before jenkins_pebble_ready event.
None.
jenkins_storage_mounted is migrated from state to jenkins module.
None.

fix: storage mount

---

.github/workflows/bot_pr_approval.yaml

Applicable spec: ISD115
Adds a workflow file that triggers `operator-workflows` for the purpose of providing 1 approval in case of a bot PR
To make it possible for 1 person to manage bot PRs rather than having to wait for an additional review
N/A
N/A
N/A

add workflow for bot approval

---

.github/workflows/bot_pr_approval.yaml

Applicable spec: ISD115
Got the name of the workflow file wrong 😞 
N/A
N/A
N/A
N/A

correct workflow file name

---

tests/integration/conftest.py
tests/integration/test_machine_agent.py

Applicable spec: None.
The edge version of Jenkins machine charm deprecates the `label` configuration option.
This PR updates the deprecated `label`.
To update the label configuration option used in latest Jenkins machine agent charm.
https://charmhub.io/jenkins-agent/configure?channel=latest/edge
None.
`test/integration/conftest.py` - to deploy jenkins agent machine charm with updated configuration option.
None.

test: update deprecated label

---

config.yaml
tests/integration/test_plugins.py

Add an integration test for the docker-build-publish plugin.
We need to keep track of plugin functionality when updating the charm
N/A
N/A
N/A

Add Docker plugin test

---

config.yaml
tests/integration/test_plugins.py

Add an integration test for a commonly used plugin.
We need to keep track of plugin functionality when updating the charm
N/A
N/A
N/A

Add pipeline-groovy-lib plugin test

---

tox.ini

Add tox build pipeline for easy building and testing of Jenkins.
For novel charmers to Jenkins-k8s-operator, they might not have background information on how to build and test, given tox integration test requires many extra arguments. This simplifies the whole process to `tox -e build` and `tox -e integration`.
None.
None.
None.

feat: tox build pipeline

---

config.yaml
tests/integration/test_plugins.py

Add an integration test for the dependency-check-jenkins-plugin
Keeping track of the plugin's functionality
N/A
N/A
N/A

Add OWASP dependency check test

---

.github/workflows/integration_test.yaml
src/ingress.py
src/jenkins.py
tests/integration/conftest.py
tests/integration/test_ingress.py

Enable ingress integration test
The existing integration test for the ingress v2 relation is not being executed
N/A
N/A
N/A

Enable ingress integration test

---

.github/workflows/integration_test.yaml
.trivyignore
config.yaml
docs/how-to/integrate-with-external-agents.md
metadata.yaml
src-docs/agent.py.md
src-docs/charm.py.md
src-docs/ingress.py.md
src-docs/jenkins.py.md
src-docs/state.py.md
src/agent.py
src/charm.py
src/ingress.py
src/jenkins.py
src/state.py
tests/integration/conftest.py
tests/integration/test_ingress.py
tests/unit/test_agent.py
tests/unit/test_jenkins.py
tests/unit/test_state.py

Applicable spec: ISD-126 (internal)
It's currently not possible for the [Jenkins charm](https://charmhub.io/jenkins-k8s) to establish a working cross-model relation with [machine agent charms ](https://charmhub.io/jenkins-agent)that does not have access to the k8s pod IP (only possible in microk8s) and with k8s agent charms that are not in the same cluster due to the Pod IP being hard-coded in the relation data bag.
This PR will add another ingress integration, called `agent-discovery-ingress`, which will be used for external agent discovery.
This PR will also enable websocket for all inbound agent connections. Using WebSocket, inbound agents can now be connected much more simply when a reverse proxy is present: if the HTTP(S) port is already serving traffic, most proxies will allow …

ISD-1622 Jenkins agent discovery with ingress

---

.github/workflows/integration_test.yaml
src-docs/actions.py.md
src-docs/agent.py.md
src-docs/ingress.py.md
src/actions.py
src/agent.py
src/ingress.py
tests/integration/conftest.py
tests/integration/test_ingress.py
tests/unit/test_jenkins.py

Applicable spec: <link> N/A
URL prefix doesn't need to be removed as it has to be present on the requests for integration with oathkeeper to work properly.
Also simplifies the integration tests and aligns them with oathkeeper requirements
N/A
N/A
ingress.py

Do not strip ingress prefix

---

tests/integration/files/identity-bundle-edge-patched.yaml

New oci-image rev of the identity team's [login-ui-operator](https://charmhub.io/identity-platform-login-ui-operator/resources/oci-image) is breaking charm revision 79

pin resource rev due to instability

---

docs/how-to/configure-jenkins-memory-usage.md
src/pebble.py

based on https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/best-practices/jvm-memory-settings-best-practice
Following internal discussion, we have decided to add these JVM options when starting pebble to use together with juju constraints to manage the available memory for a jenkins-k8s charm.

ISD-1729 Add RAM percentage JVM option and documentations

---

jenkins_rock/rockcraft.yaml
src-docs/agent.py.md
src-docs/auth_proxy.py.md
src-docs/jenkins.py.md
src-docs/pebble.py.md
tests/integration/test_plugins.py

Regular update to new Jenkins LTS version
New Jenkins LTS version is available

jenkins version 2.440.3

---

src-docs/charm.py.md
src/charm.py

During charm upgrade, when not using `agent-discovery-ingress`, the Pod IP address of the jenkins charm unit changes, leading to disconnection of agents. This PR adds `self.agent_observer.reconfigure_agent_discovery(event)` to the `_on_charm_upgrade` hook to update the discovery address in the relation databag. Note that since the secrets used by the agents are calculated based on the agent's node name, this value stays the same between charm upgrades.

ISD-1846 Refresh agent relation on charm upgrade

---

src-docs/ingress.py.md
src/ingress.py

Fix typo in docstrings

---

charmcraft.yaml
tests/conftest.py

- Fix broken dependency chain build (rpds-py) by building rustc ourselves. (build-package `rust-all` version 1.75 is not supported by rpds-py)
- To build the charm.

fix: build

---

charmcraft.yaml

Fixed upstream: https://github.com/pypa/setuptools/commit/441799f8b45a1a01c608db49333403db1b0d7100#diff-61d113525e9cc93565799a4bb8b34a68e2945b8a3f7d90c81380614a4ea39542R7

revert setuptools breaking dep issue (fixed upstream)

---

CONTRIBUTING.md
docs/tutorial/getting-started.md
tests/integration/test_plugins.py
tests/unit/test_jenkins.py

Standarise the Jenkins tutorial with other tutorials and improve/fix the tutorial.

Standardise and improve Jenkins tutorial

---

jenkins_rock/rockcraft.yaml

Upgrade Jenkins to [2.492.1](https://www.jenkins.io/changelog/2.492.1/)
To keep up to date with the LTS version
None
None
None

Update Jenkins to 2.492.1

---

README.md
jenkins_rock/rockcraft.yaml

Bumps Jenkins to 2.492.2
To keep up with the latest LTS
None
None
None

Bump Jenkins to 2.492.2

---

tests/integration/conftest.py

This pull request aims to fix the [issue](https://github.com/canonical/kratos-operator/issues/386) by bumping the identity-platform-login-ui-operator charm's version. The failure is due to a recent `ui-endpoint-info` library update.

fix: fix the auth test by bumping login ui revision

---

docs/changelog.md
src/agent.py
src/auth_proxy.py
src/jenkins.py
tests/integration/pre_run_script.sh
tests/unit/conftest.py
tests/unit/test_agent.py
tests/unit/test_jenkins.py

- Addresses issue with race condition of agent-related hook firing before service ready. https://github.com/canonical/jenkins-k8s-operator/issues/193
- When relating the agents before Jenkins server charm is initialized (the case of terraform where everything runs in parallel), the hook will continue waiting for the Jenkins node registration even if the underlying Jenkins service is not ready. Add a check to prevent such race condition from happening.

fix: agent relation race condition

---

docs/changelog.md
src/agent.py
src/charm.py
src/state.py
tests/integration/test_external_agent.py
tests/unit/test_agent.py
tests/unit/test_state.py

Applicable spec: <link> N/A
- Fixes issue: https://github.com/canonical/jenkins-k8s-operator/issues/194
- The Jenkins server URL is configured when ingress is available. This makes the agent nodes lose connection to the server since the server URL has been updated. This PR fixes such behavior.

fix: agent connectivity on server ingress relation

---

docs/changelog.md
src/charm.py

- Reconcile agents on charm upgrade
- Previous revisions may not have the agents reconciled - fixes: #268 
- On refresh charm, the agent is reconciled.
No user facing changes.

fix: reconcile agents on upgrade charm
