jenkins_rock/rockcraft.yaml, src/charm.py, src/jenkins.py
This PR runs Jenkins as a non-root user. User "jenkins" with UID 2000 and group "jenkins" with GID 2000 has been added.
=> fix: run jenkins as jenkins non-root

.github/workflows/auto_update_libs.yaml, .github/workflows/promote_charm.yaml, .github/workflows/publish_charm.yaml
This PR adds the missing workflows from operator-workflows.
=> feat: add all workflows from operator-workflows

.github/workflows/promote_charm.yaml
This PR enables automated documentation upload via `upload-charm-docs` module.
=> feat: enable upload-charm-docs

tests/integration/files/postbuildscript_plugin_job_xml.j2, tests/integration/test_plugins.py
Adds a functionality test to the post-build-script plugin.
To support commonly used plugins.
None.
None. 
None.
=> test: postbuildscript

tests/integration/test_plugins.py
Test the backup of thinBackup plugin.
Commonly used plugin support.
None.
None.
None.
=> test: thinbackup plugin

tests/integration/test_plugins.py
Test the API endpoint enabled by rebuild plugin.
Integration test for supported plugins.
None.
None.
None.
=> test: rebuild plugin

tests/integration/test_plugins.py
Fixes breaking rebuilder plugin integration test.
To let other PRs pass!
None.
None.
None.
=> test: fix rebuilder test

.github/workflows/integration_test.yaml, src/charm.py, tests/integration/test_jenkins.py, tests/unit/test_charm.py
Fix storage mount permission issue on certain environments
=> ISD-1307 Update permission when mounting storage

jenkins_rock/rockcraft.yaml
Update Jenkins version to 2.427
Trivy needs the version update for the checks to pass.
N/A
N/A
N/A
=> Update Jenkins version

tests/integration/test_plugins.py
=> Change container name from jenkins-k8s-agent to jenkins-agent-k8s

src-docs/agent.py.md, src-docs/charm.py.md, src-docs/ingress.py.md, src/agent.py, tests/unit/test_agent.py
Applicable spec: <link> N/A
Follow up #115 
N/A
N/A
agent.py
N/A
=> Fix jenkins agent discovery

.github/workflows/integration_test.yaml, src-docs/jenkins.py.md, src/actions.py, src/agent.py, src/charm.py, src/jenkins.py, tests/integration/conftest.py, tests/unit/conftest.py, tests/unit/test_actions.py, tests/unit/test_charm.py, tests/unit/test_jenkins.py, tests/unit/test_timerange.py
Applicable spec: <link> N/A
Refactor in preparation of the jenkins oathproxy integration
N/A
N/A
actions.py
agent.py
charm.py
jenkins.py
N/A
=> Refactor jenkins.py

docs/how-to/resize-jenkins-storage.md
Add documentation on how to resize the jenkins-home storage volume.
=> ISD-1656 Add resize storage documentation

docs/how-to/resize-jenkins-storage.md, tests/integration/test_plugins.py
Update backup guide to be copy-pasteable & fix some bugs with pathing.
:)
=> docs: update backup file docs

jenkins_rock/rockcraft.yaml
Upgrade Jenkins version to 2.452.1
So we get the latest security fixes
None
None
None
=> Go to 2.452.1

.github/workflows/integration_test.yaml, charmcraft.yaml, jenkins_rock/rockcraft.yaml
Upgrade to the latest Jenkins LTS
To keep up to date with upstream
=> Upgrade Jenkins to 2.462.1

.trivyignore, jenkins_rock/rockcraft.yaml
Upgrades the Jenkins version to the latest LTS
To keep the charm up to date
N/A
N/A
N/A
=> Upgrade Jenkins to 2.462.2

.trivyignore, jenkins_rock/rockcraft.yaml, tests/integration/conftest.py
- Bump patch version
No code changes are made - just bumping the version :)
=> chore: update jenkins (patch increment)

tests/integration/conftest.py, tests/integration/test_cos.py
=> Fix integration tests

CONTRIBUTING.md, README.md, docs/explanation/agent-deprecated-relation.md, docs/explanation/charm-architecture.md, docs/how-to/integrate-with-external-agents.md, docs/how-to/integrate-with-iam.md, docs/how-to/integrate-with-machine-agents.md, docs/how-to/redeploy.md, docs/index.md, docs/reference/integrations.md, docs/tutorial/getting-started.md
Fix Vale errors.
Vale is giving out errors and we are trying to make every documentation compliant with it.
No need to update changelog.
=> Fix Vale errors

charmcraft.yaml, docs/changelog.md, docs/explanation/charm-architecture.md, tests/integration/conftest.py
No charm/application logic changes.
=> chore: update charm to use noble base

docs/changelog.md, src/state.py, tox.ini
- Fixes issue: #275 
- Some relation omitted due to naming.
=> fix: issue with jenkins name omitting relations

.github/workflows/integration_test.yaml, pyproject.toml, src/charm.py, src/jenkins.py, src/pebble.py, src/storage.py, tests/integration/conftest.py, tests/unit/test_charm.py, tox.ini
Factor out storage reconciler.
To drive the project into holistic charm. Too many race conditions and undetermined hook firing sequence.
No user facing changes, semantic stays the same.
=> chore: storage reconciler refactor
